# Copyright 2026  Canonical Ltd.
# See LICENSE file for licensing details.

name: Run tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  integration:
    runs-on: ${{ matrix.system.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        system:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
        env: [integration]
        k8s_version:
          # - 1.32-strict/stable 
          - 1.34-strict/stable
      fail-fast: false
    steps:
      - name: Disk cleanup
        shell: bash
        run: |
          sudo rm -rf \
            /opt/google \
            /opt/hostedtoolcache \
            /opt/microsoft/powershell \
            /opt/microsoft/msedge \
            "$AGENT_TOOLSDIRECTORY" \
            /usr/lib/firefox \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/gradle* \
            /usr/share/miniconda \
            /usr/share/sbt \
            /usr/share/swift \
            /home/linuxbrew
          pipx uninstall-all
          printf '\nDisk usage\n'
          df --human-readable

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install tooling
        run: |
          sudo snap install concierge --classic
          sudo snap install yq
          cat tests/resources/concierge_ci.yaml | yq '.providers.microk8s.channel = "${{ matrix.k8s_version }}"' > edited_concierge.yaml
          sudo concierge prepare -c edited_concierge.yaml

          sudo microk8s config | tee /home/runner/.kube/config

      - name: Setup microceph
        id: microceph
        run: |
          sudo microceph cluster bootstrap
          sudo microceph disk add loop,1G,3
          sudo microceph enable rgw
          sudo microceph.radosgw-admin user create --uid test --display-name test --access-key=foo --secret-key=bar
          export IP=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
          echo -e "S3_ENDPOINT=http://$IP:80/\nS3_ACCESS_KEY=foo\nS3_SECRET_KEY=bar" > .env

          # Create bucket and path
          export AWS_ACCESS_KEY_ID="foo"
          export AWS_SECRET_ACCESS_KEY="bar"
          export AWS_ENDPOINT_URL="http://${IP}:80"

          aws s3 mb s3://test-polaris

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: polaris-${{ matrix.system.arch }}
          path: polaris

      - name: Load test image
        run: |
          sudo mv polaris/*.tar .
          sudo microk8s ctr images import $(find . -type f -name "*.tar")

      - name: Run tests
        run: |
          just test-rock
